CLASS zfi003_cl_dd_behaviour DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF zfi003_dd_behaviour.
  CLASS-DATA: gt_table  TYPE TABLE FOR ACTION IMPORT i_journalentrytp~Post,
              gv_pid    TYPE abp_behv_pid.
ENDCLASS.



CLASS ZFI003_CL_DD_BEHAVIOUR IMPLEMENTATION.
ENDCLASS.
